[build]
  # Build command (if needed for processing)
  command = "echo 'Static site - no build needed'"
  
  # Directory to publish
  publish = "."
  
  # Functions directory (for Netlify Functions)
  functions = "netlify/functions"

[build.environment]
  # Environment variables for build
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"

# Redirect rules
[[redirects]]
  # SPA routing - redirect all routes to index.html for client-side routing
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"], Country = ["US"]}

# API proxy for development (when using external API)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-api.com/api/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "netlify"}

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: blob:;
      connect-src 'self' https://api.netlify.com;
    """
    
    # Performance headers
    Cache-Control = "public, max-age=31536000"

# Specific headers for API routes (if using Netlify Functions)
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Headers for HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Headers for static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Error pages
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Form handling (if you have contact forms)
[[forms]]
  name = "contact"
  
# Environment-specific configurations
[context.production.environment]
  NODE_ENV = "production"
  API_URL = "https://your-production-api.com"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  API_URL = "https://your-staging-api.com"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  API_URL = "https://your-dev-api.com"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.audits]
    performance = true
    accessibility = true
    best-practices = true
    seo = true
    
  [plugins.inputs.settings]
    output_path = "reports/lighthouse.html"

# Build processing
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true
  
[build.processing.js]
  bundle = true
  minify = true
  
[build.processing.html]
  pretty_urls = true
  
[build.processing.images]
  compress = true

# Custom domains (configure as needed)
# [[domain_redirects]]
#   from = "old-domain.com"
#   to = "new-domain.com"
#   status = 301
#   force = true

# Split testing (A/B testing)
# [[splits]]
#   path = "